# Generated by Django 2.2.4 on 2019-08-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='地点')),
                ('administrator', models.CharField(blank=True, max_length=255, null=True, verbose_name='实验员')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='实验室名称')),
            ],
            options={
                'verbose_name': '实验室信息',
                'verbose_name_plural': '实验室信息',
            },
        ),
    ]
