# Generated by Django 2.2.4 on 2019-08-10 02:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('image', models.ImageField(blank=True, default='image/2019/image.png', max_length=255, null=True, upload_to='image/%Y', verbose_name='图片')),
                ('content', models.TextField(default=None, verbose_name='内容')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('priority', models.IntegerField(default=1000, verbose_name='优先级')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None, max_length=1024)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
            },
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_num', models.IntegerField(default=0, verbose_name='设备损坏数量')),
                ('reagent_num', models.IntegerField(default=0, verbose_name='试剂消耗数量')),
                ('instrument_num', models.IntegerField(default=0, verbose_name='仪器损坏数量')),
                ('addition', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_approve', models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=True)),
            ],
            options={
                'verbose_name': '耗材报告',
                'verbose_name_plural': '耗材报告',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('credits', models.FloatField(max_length=5, verbose_name='学分')),
                ('day', models.CharField(choices=[('Monday', '周一'), ('Tuesday', '周二'), ('Wednesday', '周三'), ('Thursday', '周四'), ('Friday', '周五'), ('Saturday', '周六'), ('Sunday', '周日')], default='Monday', max_length=9, verbose_name='日')),
                ('section', models.CharField(choices=[('one', '第一节'), ('two', '第二节'), ('three', '第三节'), ('four', '第四节'), ('five', '第五节'), ('six', '第六节'), ('seven', '第七节'), ('eight', '第八节'), ('nine', '第九节'), ('ten', '第十节')], default='one', max_length=5, verbose_name='节次')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('context', models.TextField(default=None, verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
            ],
            options={
                'verbose_name': '实验报告',
                'verbose_name_plural': '实验报告',
            },
        ),
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('term', models.CharField(max_length=5, verbose_name='季度')),
            ],
            options={
                'verbose_name': '实验室课表',
                'verbose_name_plural': '实验室课表',
            },
        ),
        migrations.CreateModel(
            name='ThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '点赞信息',
                'verbose_name_plural': '点赞信息',
            },
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('term', models.CharField(max_length=5, verbose_name='季度')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课表',
                'verbose_name_plural': '课表',
            },
        ),
    ]
