# Generated by Django 2.2.4 on 2019-08-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='设备名')),
                ('decription', models.TextField(default=None, verbose_name='设备使用')),
                ('sum', models.IntegerField(verbose_name='设备总数')),
                ('rest', models.IntegerField(verbose_name='设备剩余数')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='仪器名')),
                ('decription', models.TextField(default=None, verbose_name='仪器使用')),
                ('sum', models.IntegerField(default=0, verbose_name='仪器总数')),
                ('rest', models.IntegerField(default=0, verbose_name='仪器剩余数')),
            ],
            options={
                'verbose_name': '仪器信息',
                'verbose_name_plural': '仪器信息',
            },
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='试剂名')),
                ('decription', models.TextField(default=None, verbose_name='试剂使用说明')),
                ('sum', models.IntegerField(default=0, verbose_name='试剂总数')),
                ('rest', models.IntegerField(default=0, verbose_name='试剂剩余数')),
                ('is_harm', models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=True)),
            ],
            options={
                'verbose_name': '试剂信息',
                'verbose_name_plural': '试剂信息',
            },
        ),
    ]
